### ISSUE TITLE
scrapper

### ISSUE THREAD

**Issue by clemclemmm** [Madouc/fablab-locations#3]
Hello Madouc,

there is a probleme in the scrapper on morph.io, 
but i don't know why. 
i have correct the fab wiki table few times, and now it's good. 
i will check tomorow if morph.io has done the job, but it's not working since few days.

cheers,
Clément, France

**Comment by Madouc** [comment]
ah, the reason it is no longer working is because the yahoo geolocation api
has been ended.
https://developer.yahoo.com/maps/rest/V1/geocode.html

possible candidate for replacing is
https://developers.google.com/maps/documentation/geocoding/intro

**Comment by clemclemmm** [comment]
-____-
